### ISSUE TITLE
How to use with electron-builder?

### ISSUE THREAD

**Issue by lucasbento** [pbarbiero/basic-electron-react-boilerplate#11]
I'm trying to use this boilerplate with `electron-builder` but it throws this error on start: 

```
Uncaught Exception:
ReferenceError: document is not defined
    at Object.<anonymous> (/project/path/dist/mac/My App.app/Contents/Resources/app.asar/dist/index.js:18:25595)
    at o (/project/path/dist/mac/My App.app/Contents/Resources/app.asar/dist/index.js:1:336)
    at p (/project/path/dist/mac/My App.app/Contents/Resources/app.asar/dist/index.js:1:724)
    at Object.<anonymous> (/project/path/dist/mac/My App.app/Contents/Resources/app.asar/dist/index.js:1:735)
    at Object.<anonymous> (/project/path/dist/mac/My App.app/Contents/Resources/app.asar/dist/index.js:19:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
```

**Comment by pbarbiero** [comment]
Unfortunately I have no idea as I dont use `electron-builder`
